
[MDP]

    [MDP.general]
    episodes = 100  # "Delta" - the number of training iterations (should be large enough for convergence)
    wildfire_update_window = 10  # time units (this value represent the number of base time units that pass between updates)
    aircraft_update_window = 2  # time units (this value represent the number of base time units that pass between updates)
    hotshot_update_window = 5  # time units (this value represent the number of base time units that pass between updates)

    [MDP.plotting]
    generate_plots = false
    generate_mp4 = false

[MODEL_FREE]

    [MODEL_FREE.plotting]
    generate_plots = false
    generate_mp4 = false
