"""
-------------------------------
| Dartmouth College           |
| ENGG 199.09 - Game Theory   |
| Fall 2022                   |
-------------------------------

Boards for the MDP Model

This script will be used to store the static or dynamic "boards" that act as the basis for the 
environment object generated by envs.py. 
"""

# imports 
import numpy as np 

class board1:
    board = np.array([[0, 0, 0, 0], 
                      [0, 0, 0, 0],
                      [0, 0, 0, 0], 
                      [0, 0, 0, 0]])
    original_board = board.copy()
    board_x = board.shape[1]
    board_y = board.shape[0]
    agent_start_position = (3,3)
    fire_start_position = (0,0)
