"""
-------------------------------
| Dartmouth College           |
| ENGG 199.09 - Game Theory   |
| Fall 2022                   |
-------------------------------

Boards for the MDP Model

This script will be used to store the static or dynamic "boards" that act as the basis for the 
environment object generated by envs.py. 
"""

# imports 
import numpy as np 

class board1:
    board = np.array([[np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 0, 0, 0, 0], 
                      [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 0, 0, 0, 0],
                      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                      [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 0, 0, 0, 0], 
                      [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 0, 0, 0, 0]])
    original_board = board.copy()
    board_x = board.shape[1]
    board_y = board.shape[0]
    agent_start_position = (2,7)
    fire_start_position = (2,0)


# some plotting code 
if __name__ == "__main__":
    import numpy as np
    import seaborn as sns
    import matplotlib.pylab as plt

    data = board1.board
    ax = sns.heatmap(data, linewidth=0.5,  cmap="YlGnBu")
    plt.show()